# Generated by Django 2.2 on 2019-04-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Singapore', max_length=50),
        ),
    ]
