# Generated by Django 2.2 on 2019-04-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookMark',
        ),
    ]
