# Generated by Django 2.2 on 2019-05-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='num_of_articles',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='tag',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelResources.ArticlePost'),
            preserve_default=False,
        ),
    ]
