# Generated by Django 2.1.1 on 2019-04-09 00:57

from django.db import migrations, models
import django.db.models.deletion
import travelResources.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=travelResources.models.post_name)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelResources.ArticlePost')),
            ],
        ),
    ]
