# Generated by Django 2.1.1 on 2019-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtag',
            name='content',
            field=models.CharField(default='', max_length=1400),
            preserve_default=False,
        ),
    ]
