# Generated by Django 2.2 on 2019-04-10 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0003_locationtag_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtag',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
