# Generated by Django 2.2 on 2019-04-12 02:40

from django.db import migrations, models
import django.db.models.deletion
import travelResources.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0005_auto_20190412_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=travelResources.models.post_name)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelResources.LocationTag')),
            ],
        ),
    ]
