# Generated by Django 2.2 on 2019-04-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0006_tagimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='images',
            field=models.ManyToManyField(to='travelResources.Image'),
        ),
        migrations.AddField(
            model_name='locationtag',
            name='images',
            field=models.ManyToManyField(to='travelResources.Image'),
        ),
        migrations.DeleteModel(
            name='TagImage',
        ),
    ]
