# Generated by Django 2.2 on 2019-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0007_auto_20190412_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='images',
            field=models.ManyToManyField(related_name='post_image_list', to='travelResources.Image'),
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='images',
            field=models.ManyToManyField(related_name='tag_image_list', to='travelResources.Image'),
        ),
    ]
