# Generated by Django 2.2 on 2019-04-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelResources', '0008_auto_20190412_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='type',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='type',
            field=models.ManyToManyField(related_name='article_type', to='travelResources.Type'),
        ),
        migrations.AddField(
            model_name='locationtag',
            name='type',
            field=models.ManyToManyField(related_name='location_type', to='travelResources.Type'),
        ),
    ]
